# -*- coding: utf-8 -*-
"""CodePark2 - 28/10/22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j3YzmhKsZ-Xi-74MITebVkSZHq36PhGX
"""

def calculadora(n1,v,n2):
 if v == '+':

   return  n1 + n2

 elif v == '-' :

    return n1 - n2

 elif v == '*' :

    return  n1 * n2

 elif v == '/':

    return n1 / n2

 else:

   return 0 * 0

d1 = float(input('Digite o primeiro número:'))
p = str(input('Digite a operação:'))
d2 = float(input('Digite o segundo número:'))

resultado = calculadora(d1,p,d2)

print('Resultado:',resultado)